version: 2
jobs:
  docker:
    docker:
    - image: docker
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - run:
        name: Docker login
        command: |
          docker login -u=${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run:
        name: Install essentials
        command: |
          apk add --no-cache --virtual .build-deps make gcc
    - run:
        name: build docker image
        command: |
          make docker-build
    - run:
        name: test of docker image
        command: |
          make docker-test
    - run:
        name: publish docker image
        command: |
          make docker-push
          if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker build -t ${DOCKER_USERNAME}/zookeeper:latest .;
              docker push ${DOCKER_USERNAME}/zookeeper:latest;
          fi
  k8s:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: install minikube and kubectl
          command: make minikube-install
      - run:
          name: run minikube
          command: make minikube-run
      - run:
          name: run zookeeper tests
          command: make minikube-test
      - run:
          name: delete resources
          command: make minikube-clean
      - run:
          name: run zookeeper tests persistent
          command: make minikube-test-persistent
      - run:
          name: delete minikube
          command: make minikube-delete
  openshift:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: install oc
          command: make oc-install
      - run:
          name: run local openshift cluster
          command: make oc-cluster-run
      - run:
          name: run zookeeper tests
          command: make oc-cluster-test
      - run:
          name: clean resources
          command: make oc-clean-resources
      - run:
          name: run zookeeper persistent tests
          command: make oc-cluster-test-persistent
      - run:
          name: delete local openshift cluster
          command: make oc-cluster-clean
  gh-tag-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Install essentials
          command: |
            apk add --no-cache --virtual .build-deps make gcc
      - run:
          name: Create a new tag
          command: |
            cd ./artifacts
            VERSION=v$(make version)
            git push origin :${VERSION} > /dev/null 2>&1
            git tag ${VERSION}
            git push --tags
      - run:
          name: Create a tag release on github
          command: |
            VERSION=$(make version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b "Zookeeper version ${VERSION}" -delete ${VERSION} ./artifacts/k8s/*.yaml

workflows:
  version: 2
  build:
    jobs:
    - docker:
        filters:
          branches:
            only:
              - /^\d+\.\d+$/
    - k8s:
        requires:
          - docker
        filters:
          branches:
            only:
              - /^\d+\.\d+$/
    - openshift:
        requires:
          - docker
        filters:
          branches:
            only:
              - /^\d+\.\d+$/
    - gh-tag-release:
        requires:
          - k8s
          - openshift
        filters:
          branches:
            only:
              - /^\d+\.\d+$/
